// Lithium-ion battery industry news, aggregated by country.
// Each entry has bilingual (EN/ZH) title + description and a source link.
const NEWS_DATA = [
  {
    id: 1,
    country: "KR",
    date: "2026-10-03",
    title_en: "LG Energy Solution to Supply 46-Series Round Cells for Mercedes-Benz's Next-Gen EVs",
    title_zh: "LG新能源将为梅赛德斯-奔驰新一代电动车供应46系圆柱电芯",
    desc_en: "LG Energy Solution will supply round cells with a diameter of 46 millimetres and a height of 100 millimetres for Mercedes-Benz's next-generation electric vehicles, with deliveries set to begin in 2028, electrive reported on October 3. Korean media previously reported the underlying contracts, which cover roughly 107 GWh of 46-series cylindrical cells, of which 32 GWh is for Europe from mid-2028 and 75 GWh for the US from mid-2029.",
    desc_zh: "据electrive 10月3日报道,LG新能源将为梅赛德斯-奔驰的新一代电动车供应直径46毫米、高度100毫米的圆柱电芯,交付将于2028年开始。韩国媒体此前已报道相关合同,涉及约107吉瓦时46系圆柱电芯,其中32吉瓦时供应欧洲(自2028年年中起),75吉瓦时供应美国(自2029年年中起)。",
    source_name: "electrive",
    source_url: "https://www.electrive.com/2026/10/03/lg-energy-solution-to-supply-46100-round-cells-to-mercedes/"
  },
  {
    id: 2,
    country: "DE",
    date: "2026-10-02",
    title_en: "BMW Opens Irlbach-Straßkirchen Plant and Starts Series Production of Gen6 Batteries",
    title_zh: "宝马启用伊尔巴赫-施特拉斯基兴工厂,第六代电池正式投入量产",
    desc_en: "BMW has opened its new battery plant in Irlbach-Straßkirchen, Lower Bavaria, and started series production just two and a half years after construction began. The site supplies the Munich plant with sixth-generation high-voltage batteries for the new BMW i3 and is set to serve as a hub for Gen6 batteries for other German plants. The Gen6 pack marks BMW's first 800-volt architecture and uses large-format 46-millimetre cylindrical cells that offer around 20% higher energy density than the previous prismatic cells.",
    desc_zh: "宝马在巴伐利亚下巴伐利亚州伊尔巴赫-施特拉斯基兴(Irlbach-Straßkirchen)的新电池工厂正式启用并投入量产,距开工建设仅两年半。该工厂为慕尼黑工厂供应新款BMW i3所用的第六代高压电池,并将成为向德国其他工厂供应第六代电池的中心枢纽。第六代电池首次采用宝马的800伏架构和直径46毫米的大圆柱电芯,能量密度较此前的方形电芯提高约20%。",
    source_name: "electrive",
    source_url: "https://www.electrive.com/2026/10/02/bmw-begins-gen6-battery-production-in-irlbach-straskirchen/"
  },
  {
    id: 3,
    country: "CN",
    date: "2026-10-02",
    title_en: "CATL Extends Lead in Global EV Battery Installations Through August as BYD Holds Second at 15.1%",
    title_zh: "1-8月全球动力电池装机量:宁德时代领先优势扩大,比亚迪以15.1%份额居次席",
    desc_en: "CnEVPost's tally of global EV battery installations for January-August 2026 shows CATL at 333.0 GWh, up 25.2% year on year, lifting its global share to 39.4% from 37.7% a year earlier. BYD ranked second with a 15.1% share (127.9 GWh), followed by LG Energy Solution at 8.1% (68.3 GWh) and CALB at 5.3% (44.4 GWh), while SK On held 2.9% with 24.9 GWh. Total global EV battery usage reached 844.2 GWh over the eight months, up 19.7% year on year.",
    desc_zh: "CnEVPost统计的2026年1-8月全球动力电池装机数据显示,宁德时代装机量达333.0吉瓦时,同比增长25.2%,全球份额由去年同期的37.7%升至39.4%。比亚迪以15.1%的份额(127.9吉瓦时)位列第二,其后是LG新能源(8.1%,68.3吉瓦时)和中创新航(5.3%,44.4吉瓦时),SK On份额为2.9%,装机24.9吉瓦时。前八个月全球动力电池总装机量为844.2吉瓦时,同比增长19.7%。",
    source_name: "CnEVPost",
    source_url: "https://cnevpost.com/2026/10/02/global-ev-battery-market-share-jan-aug-2026/"
  },
  {
    id: 4,
    country: "FI",
    date: "2026-10-01",
    title_en: "Wärtsilä and RCT Solutions Close Storage JV, Launch Utility-Scale Integrator Valo",
    title_zh: "瓦锡兰与RCT Solutions完成储能合资交割,大型储能集成商Valo正式成立",
    desc_en: "Wärtsilä and Germany's RCT Solutions closed their joint venture for Wärtsilä's global energy storage business on October 1, launching Valo, a utility-scale battery energy storage system integrator owned 50/50 by the two partners. Valo starts with more than 20 GWh across more than 130 projects worldwide, with Peter Fath, previously CEO of RCT Solutions, as CEO and Luke Witmer as chief technology officer. The deal was announced on June 15, and Wärtsilä expects the new company to remain loss-making until late 2027.",
    desc_zh: "瓦锡兰(Wärtsilä)与德国RCT Solutions于10月1日完成了瓦锡兰全球储能业务合资企业的交割,并推出大型电池储能系统集成商Valo,双方各持股50%。Valo成立之初已拥有全球130多个项目、总计超过20吉瓦时的业务规模,由此前担任RCT Solutions首席执行官的Peter Fath出任CEO,Luke Witmer担任首席技术官。该交易于6月15日宣布,瓦锡兰预计新公司在2027年底之前仍将处于亏损状态。",
    source_name: "ESS News",
    source_url: "https://www.ess-news.com/2026/10/01/wartsila-and-rct-solutions-launch-storage-integrator-valo/"
  },
  {
    id: 5,
    country: "EU",
    date: "2026-10-01",
    title_en: "T&E: EU Will Have Enough 'Made in EU' Battery Cells by 2030, Contradicting Carmakers",
    title_zh: "T&E分析:2030年欧盟本土电池电芯供应充足,与车企说法相左",
    desc_en: "Transport & Environment (T&E) concluded in an analysis of the EU's planned local-content rules that enough 'Made in EU' battery cells will be available by 2030, contradicting current claims from the automotive industry. The European Commission plans local-content provisions that would prioritise 'Made in EU' electric vehicles in public procurement and funding programmes, with special local value-creation conditions for traction batteries. The European carmakers' association ACEA has warned of a significant gap in battery supply-chain capacity, noting that a new battery factory can take nearly a decade from announcement to full-scale production, so even projects launched today might not reach full capacity until around 2035.",
    desc_zh: "欧洲运输与环境联合会(T&E)在对欧盟拟议本土含量规则的分析中得出结论:到2030年,“欧盟制造”的电池电芯供应将足够充足,这与汽车行业目前的说法相矛盾。欧盟委员会计划出台本土含量条款,在公共采购和资金支持项目中优先考虑“欧盟制造”的电动车,并对动力电池设定本土价值创造的专门条件。欧洲汽车制造商协会(ACEA)则警告称电池供应链产能存在明显缺口,指出一座新电池工厂从宣布到全面量产可能需要近十年,即便是今天启动的项目也可能要到2035年前后才能满产。",
    source_name: "electrive",
    source_url: "https://www.electrive.com/2026/10/01/te-analysis-sufficient-european-battery-cells-by-2030/"
  },
  {
    id: 6,
    country: "IN",
    date: "2026-10-01",
    title_en: "Adani Green Lifts Operational Battery Storage at Khavda to 6.63 GWh",
    title_zh: "阿达尼绿色能源将卡瓦达运营中的电池储能容量提升至6.63吉瓦时",
    desc_en: "Adani Green Energy has expanded its operational battery energy storage capacity at Khavda, Gujarat, to 6.63 GWh from 3.55 GWh in June 2026, reaching the mark within 14 months of starting on-site BESS construction. The company says this consolidates Khavda as the world's largest operational battery installation at a single location, and that it now accounts for more than 50% of India's roughly 12.6 GWh of operational BESS. Adani Green says it is on track to add over 10 GWh in FY2026-27 and targets 50 GWh of storage over the next five years.",
    desc_zh: "阿达尼绿色能源(Adani Green Energy)已将其位于古吉拉特邦卡瓦达(Khavda)的运营电池储能容量提升至6.63吉瓦时,而2026年6月时为3.55吉瓦时,从现场储能施工启动到达成这一规模仅用了14个月。公司称,这巩固了卡瓦达作为全球单一地点最大运营电池储能装置的地位,并占印度约12.6吉瓦时运营储能总量的50%以上。阿达尼绿色能源表示,2026-27财年有望新增逾10吉瓦时,并计划在未来五年内实现50吉瓦时储能容量。",
    source_name: "Oneindia",
    source_url: "https://www.oneindia.com/india/adani-green-energy-khavda-bess-6-63-gwh-012-8221401.html"
  },
  {
    id: 7,
    country: "AU",
    date: "2026-10-01",
    title_en: "Liontown Approves A$389 Million Kathleen Valley Expansion to Lift Spodumene Output Over 50%",
    title_zh: "Liontown批准3.89亿澳元Kathleen Valley扩建项目,锂精矿产量将提升逾50%",
    desc_en: "Liontown Resources took a final investment decision on October 1 to expand its Kathleen Valley lithium operation in Western Australia at a cost of A$389 million, lifting processing capacity from about 2.8 million to 4.2 million tonnes a year with a new ball mill and plant upgrades. The company targets average output of about 780,000 dry tonnes a year of 5.4% Li2O spodumene concentrate over the first five years from FY30, an increase of more than 50%. First additional production is expected in FY28 with construction complete by the end of the first half of FY29; the project is to be funded from existing cash and operating cash flow and is expected to create 210 construction and 185 ongoing jobs.",
    desc_zh: "Liontown Resources 10月1日做出最终投资决定,将投入3.89亿澳元扩建其位于西澳大利亚的Kathleen Valley锂矿,通过新增球磨机及设备升级,把年处理能力从约280万吨提高到420万吨。公司目标是自2030财年起的前五年,年均产出约78万干吨、氧化锂品位5.4%的锂辉石精矿,增幅超过50%。预计2028财年开始产生新增产量,2029财年上半年末完成建设;项目资金来自现有现金和经营现金流,预计创造210个建设岗位和185个长期运营岗位。",
    source_name: "Mining.com.au",
    source_url: "https://mining.com.au/liontown-approves-389-million-kathleen-valley-expansion/"
  },
  {
    id: 8,
    country: "FR",
    date: "2026-09-30",
    title_en: "Battery Shortage: Stellantis to Pause EV Production at Sochaux and Rennes in France",
    title_zh: "电池短缺:Stellantis将暂停法国索肖和雷恩工厂的电动车生产",
    desc_en: "Stellantis is temporarily halting production at its Sochaux and Rennes plants in France because of a shortage of batteries from ACC, the battery joint venture whose cell output has struggled to ramp up. French reports say the pauses are planned for late October and cite insufficient ACC supply for long-range versions of its electric models, including the Peugeot 3008 and 5008 built at Sochaux and the Citroën C5 Aircross built at Rennes, while demand remains strong.",
    desc_zh: "由于电池合资企业ACC供应不足,Stellantis将暂时停产其位于法国的索肖(Sochaux)和雷恩(Rennes)工厂,ACC的电芯产能爬坡一直不顺。法国媒体报道称,停产计划安排在10月下旬,原因是ACC为长续航版电动车型提供的电池不足,涉及索肖工厂生产的标致3008、5008以及雷恩工厂生产的雪铁龙C5 Aircross,而这些车型的市场需求依然强劲。",
    source_name: "electrive",
    source_url: "https://www.electrive.com/2026/09/30/battery-shortage-stellantis-pauses-ev-production-in-france/"
  },
  {
    id: 9,
    country: "US",
    date: "2026-09-30",
    title_en: "GM and LG's Ultium Cells to Convert Tennessee Plant for Prismatic LMR Cell Production by 2028",
    title_zh: "通用与LG合资的Ultium Cells将改造田纳西工厂,2028年量产棱柱形LMR电芯",
    desc_en: "Ultium Cells, the joint venture of General Motors and LG Energy Solution, said it will produce prismatic lithium manganese-rich (LMR) cells at its Spring Hill, Tennessee plant, with conversion work starting late this year and production preparations complete in 2028. The companies say LMR can match the cost of lower-cost LFP cells while offering about 33% higher energy density, aimed first at electric pickups and large SUVs. The roughly $1 billion project is expected to add about 500 jobs at a site that employs around 1,200 people, and could make Spring Hill the first plant to mass-produce prismatic LMR cells.",
    desc_zh: "通用汽车与LG新能源的合资企业Ultium Cells表示,将在田纳西州斯普林希尔(Spring Hill)工厂生产棱柱形锰基富锂(LMR)电芯,改造工程将于今年晚些时候启动,2028年完成量产准备。双方称,LMR电芯成本可与低成本的磷酸铁锂电芯相当,能量密度却高出约33%,将优先用于电动皮卡和大型SUV。该项目投资约10亿美元,预计在目前约有1200名员工的工厂新增约500个岗位,斯普林希尔有望成为全球首个量产棱柱形LMR电芯的工厂。",
    source_name: "electrive",
    source_url: "https://www.electrive.com/2026/09/30/ultium-cells-retrofits-tennessee-plant-for-lmr-cell-production/"
  },
  {
    id: 10,
    country: "CN",
    date: "2026-09-30",
    title_en: "China Lithium Carbonate Futures Fall About 25% in September as Demand Fears and a Mine Licence Loss Weigh",
    title_zh: "9月中国碳酸锂期货下跌约25%,需求担忧与矿山失去许可证双重施压",
    desc_en: "Lithium carbonate futures on the Guangzhou exchange fell below 120,000 yuan ($17,900) per ton by the end of September from above 160,000 yuan at the start of the month, a drop of roughly a quarter, while spot prices settled around 117,700-120,500 yuan per ton. Reports link the slide to fears over battery demand growth and to CATL's Jianxiawo mine, China's largest lithium mine, losing its licence and returning to care and maintenance. Producers meanwhile reported strong first-half profits, with Tianqi's profit up 49-fold and Zijin's lithium output up 496% year on year.",
    desc_zh: "截至9月底,广州期货交易所碳酸锂期货价格跌破12万元/吨,而月初曾高于16万元/吨,单月跌幅约四分之一;现货价格则在11.77万至12.05万元/吨区间。报道将此轮下跌归因于市场对电池需求增长的担忧,以及宁德时代枧下窝矿(中国最大锂矿)失去许可证并转入停产维护。与此同时,锂生产商公布了强劲的上半年业绩:天齐锂业利润增长49倍,紫金矿业锂产量同比增长496%。",
    source_name: "Bloomberg",
    source_url: "https://www.bloomberg.com/news/articles/2026-09-30/lithium-plunges-25-in-china-on-fears-over-battery-demand-growth"
  },
  {
    id: 11,
    country: "IT",
    date: "2026-09-30",
    title_en: "ZE Energy Acquires 200 MW/1 GWh-Plus 'Elena' Battery Project in Apulia, Italy",
    title_zh: "法国ZE Energy收购意大利普利亚大区200兆瓦/1吉瓦时以上“Elena”储能项目",
    desc_en: "French power producer ZE Energy has acquired the fully permitted, construction-ready Elena project, a 200 MW battery system with more than six hours of storage duration in Troia, Apulia, from UK developer Aura Power. The project has a secured connection to Italy's 380 kV transmission network and lifts ZE Energy's standalone Italian BESS portfolio to about 300 MW, including the 98.5 MW/895 MWh Sessa Aurunca project co-developed with Octopus Energy Generation. ZE Energy targets 1.5 GW of installed capacity by 2030 across France, Italy, and Germany.",
    desc_zh: "法国电力生产商ZE Energy从英国开发商Aura Power手中收购了位于意大利普利亚大区特罗亚(Troia)的“Elena”项目,该项目已取得全部许可、具备开工条件,功率200兆瓦,储能时长超过六小时,并已获得接入意大利380千伏输电网的许可。此次收购使ZE Energy在意大利的独立储能项目组合增至约300兆瓦,其中包括与Octopus Energy Generation共同开发的98.5兆瓦/895兆瓦时Sessa Aurunca项目。ZE Energy的目标是到2030年在法国、意大利和德国实现1.5吉瓦装机。",
    source_name: "ESS News",
    source_url: "https://www.ess-news.com/2026/09/30/ze-energy-acquires-1-gwh-plus-bess-project-in-italy/"
  },
  {
    id: 12,
    country: "AU",
    date: "2026-09-28",
    title_en: "Gamuda Wins A$790 Million EPC Deal for First Stage of Mortlake Energy Hub, With 1,449 MWh Battery",
    title_zh: "Gamuda获7.9亿澳元EPC合同,承建Mortlake能源枢纽一期及1449兆瓦时储能系统",
    desc_en: "Malaysia's Gamuda signed an A$790 million engineering, procurement and construction contract for the first stage of the Mortlake Energy Hub in Victoria, comprising a 435 MWp solar farm and a 1,449 MWh battery energy storage system connecting to the 500 kV network at Mortlake Terminal Station. Energization is expected in April 2028, with completion targeted for January 2029 and operations starting in the first quarter of 2029. A separate A$45 million operation and maintenance contract is expected to follow within a month.",
    desc_zh: "马来西亚Gamuda公司签署了维多利亚州Mortlake能源枢纽一期的7.9亿澳元EPC(设计、采购、施工)合同,项目包括435兆瓦峰值光伏电站和1449兆瓦时电池储能系统,并通过Mortlake终端变电站接入500千伏电网。项目预计2028年4月通电,目标2029年1月竣工,2029年第一季度投入运营。另有一份4500万澳元的运维合同预计将在一个月内签订。",
    source_name: "ESS News",
    source_url: "https://www.ess-news.com/2026/09/28/first-stage-bess-at-mortlake-energy-hub-grows-to-1449-mwh-as-epc-deal-signed/"
  },
  {
    id: 13,
    country: "UA",
    date: "2026-09-28",
    title_en: "Ukraine Adds Up to 1.9 GWh of Battery Storage in First Half of 2026, Industry Group Says",
    title_zh: "乌克兰太阳能协会:2026年上半年乌克兰新增电池储能容量最高达1.9吉瓦时",
    desc_en: "The Solar Energy Association of Ukraine (SEAU) said on September 28 that preliminary estimates put the country's battery storage additions at between 1.6 and 1.9 GWh in the first half of 2026, alongside roughly 1.1 GW of new solar capacity, as war-driven grid instability continues to push both utilities and households toward storage. SEAU expects full-year 2026 additions to reach around 3.2 GWh, building on the 2.9 GWh installed in 2025 that made Ukraine the fourth-largest battery storage market in Europe last year. Distributed systems under 1 MW, largely for self-consumption, account for roughly 80% of new installations by number.",
    desc_zh: "乌克兰太阳能协会(SEAU)9月28日表示,根据初步测算,该国2026年上半年新增电池储能容量介于1.6至1.9吉瓦时之间,同期新增太阳能装机约1.1吉瓦,持续的战时电网不稳定局面正推动公用事业机构与家庭用户加快部署储能。SEAU预计2026全年新增储能将达约3.2吉瓦时,在2025年新增2.9吉瓦时的基础上继续增长,使乌克兰跻身去年欧洲第四大电池储能市场。按数量计,1兆瓦以下、主要用于自发自用的分布式系统约占新增装机的80%。",
    source_name: "Energy-Storage.News",
    source_url: "https://www.ess-news.com/2026/09/28/ukraine-adds-between-1-6-1-9-gwh-of-energy-storage-in-h1-2026/"
  },
  {
    id: 14,
    country: "ES",
    date: "2026-09-28",
    title_en: "Gotion and Volkswagen's PowerCo Plan €3.22 Billion Battery Ventures in Spain, Slovakia and Morocco",
    title_zh: "国轩高科与大众旗下PowerCo计划投资32.2亿欧元,在西班牙、斯洛伐克和摩洛哥布局电池项目",
    desc_en: "Gotion High-Tech and Volkswagen announced on September 28 plans to jointly invest about €3.22 billion ($3.67 billion) in battery and materials projects through three joint ventures, with Gotion contributing about €1.6 billion and PowerCo about €1.62 billion in stages. The largest is in Valencia, Spain, with about €2.26 billion for 29.1 GWh of annual capacity, where Gotion would take 49% of PowerCo Spain; the partners would also invest about €480 million in 8.4 GWh at Šurany, Slovakia, and about €480 million in a 100,000-tonne LFP cathode materials plant in Kenitra, Morocco. Each project is expected to take no more than five years to build.",
    desc_zh: "国轩高科与大众集团9月28日宣布,计划通过三家合资企业共同投资约32.2亿欧元(约36.7亿美元)建设电池及材料项目,其中国轩高科出资约16亿欧元,PowerCo出资约16.2亿欧元,分阶段投入。最大的项目位于西班牙巴伦西亚,投资约22.6亿欧元,年产能29.1吉瓦时,国轩高科将通过增资持有PowerCo西班牙公司49%的股权;双方还将在斯洛伐克舒拉尼投资约4.8亿欧元建设8.4吉瓦时产能,并在摩洛哥盖尼特拉投资约4.8亿欧元建设年产10万吨的磷酸铁锂正极材料项目。各项目预计建设周期不超过五年。",
    source_name: "CnEVPost",
    source_url: "https://cnevpost.com/2026/09/28/gotion-vw-plan-investment-european-battery-chain"
  },
  {
    id: 15,
    country: "SK",
    date: "2026-09-25",
    title_en: "InoBat's Nasdaq Filing Shows 2025 Loss and 20% Stake in Gotion Slovakia Gigafactory",
    title_zh: "InoBat的纳斯达克上市文件显示:2025年亏损,并持有国轩斯洛伐克超级工厂20%股权",
    desc_en: "Slovak battery maker InoBat's Nasdaq filing, reported by Energy-Storage.News on September 25, shows a 2025 loss and a 20% stake in its gigafactory joint venture with China's Gotion at Šurany, Slovakia, which is planned to start LFP cell production in 2027 with initial capacity of 20 GWh. Separately, InoBat is rebuilding its Voderady site to add a BESS module, pack and container assembly line with a targeted 5 GWh of annual capacity, able to build up to four containers per day.",
    desc_zh: "斯洛伐克电池制造商InoBat向纳斯达克提交的上市文件(Energy-Storage.News于9月25日报道)显示,公司2025年出现亏损,并持有与中国国轩高科在斯洛伐克舒拉尼(Šurany)合资超级工厂20%的股权,该工厂计划2027年开始生产磷酸铁锂电芯,初期规划产能20吉瓦时。此外,InoBat正在改造其Voderady基地,新增储能模组、电池包及集装箱组装产线,目标年产能5吉瓦时,最高可日产四个储能集装箱。",
    source_name: "Energy-Storage.News",
    source_url: "https://www.ess-news.com/2026/09/25/inobats-nasdaq-filing-shows-2025-loss-20-stake-in-gotion-gigafactory/"
  },
  {
    id: 16,
    country: "PL",
    date: "2026-09-25",
    title_en: "Greenvolt Starts Building 600 MW/2.4 GWh Siedlce BESS in Poland, One of Europe's Largest",
    title_zh: "Greenvolt在波兰启动600兆瓦/2.4吉瓦时Siedlce储能项目建设,规模居欧洲前列",
    desc_en: "Portuguese-founded independent power producer Greenvolt Power began construction around September 24-25 on its 600 MW/2.4 GWh Siedlce battery energy storage project in eastern Poland, which will be one of Europe's largest BESS facilities once complete. BYD Energy Storage will supply the project's batteries using its Haohan storage system under a supply agreement, extending a partnership that already covers Greenvolt's smaller Turośń Kościelna and Nowa Wieś Ełcka projects (200 MW/800 MWh each) in Poland. Commercial operation is targeted for late 2027, as CEE battery storage construction accelerates alongside similar builds now underway in Estonia and Lithuania.",
    desc_zh: "独立电力生产商Greenvolt Power约9月24日至25日在波兰东部启动其600兆瓦/2.4吉瓦时Siedlce电池储能项目的建设,该项目建成后将跻身欧洲规模最大的储能设施之列。根据供应协议,比亚迪储能(BYD Energy Storage)将采用其“浩瀚”储能系统为项目供货,这是双方合作的延续——此前已为Greenvolt在波兰的Turośń Kościelna及Nowa Wieś Ełcka两个较小项目(各200兆瓦/800兆瓦时)供货。项目商业运营目标定于2027年底,与此同时中东欧地区电池储能建设正加速推进,爱沙尼亚与立陶宛也有类似项目在建。",
    source_name: "Energy-Storage.News",
    source_url: "https://www.ess-news.com/2026/09/25/greenvolt-begins-building-600-mw-2-4-gwh-bess-in-poland/"
  },
  {
    id: 17,
    country: "BE",
    date: "2026-09-25",
    title_en: "Giga Storage Breaks Ground on 700 MW/2.8 GWh 'Green Turtle' BESS, Belgium's Largest",
    title_zh: "Giga Storage启动“绿海龟”700兆瓦/2.8吉瓦时储能项目建设,规模居比利时之首",
    desc_en: "Dutch developer Giga Storage started construction around September 25 on its 700 MW/2.8 GWh Green Turtle battery storage project on the site of a former zinc factory at the Rotem industrial estate in Dilsen-Stokkem, Limburg province — set to become Belgium's largest battery storage facility once complete. The four-hour system will use 640 Tesla Megapack 3 units, with Tesla acting as EPC contractor covering engineering, construction, battery supply, and long-term maintenance. Construction follows financial close reached in July with a ten-bank lending consortium including Rabobank, Santander, SMBC, ING, and ABN AMRO; commissioning is targeted for the end of March 2028.",
    desc_zh: "荷兰开发商Giga Storage约9月25日在比利时林堡省迪尔森-斯托克姆(Dilsen-Stokkem)罗特姆工业园区一处原锌厂旧址启动“绿海龟”(Green Turtle)700兆瓦/2.8吉瓦时电池储能项目建设,建成后将成为比利时规模最大的储能设施。这套可满负荷持续放电四小时的系统将采用640台特斯拉Megapack 3储能柜,由特斯拉担任EPC总包,负责工程设计、施工、电池供应及长期运维。项目已于7月完成融资交割,由Rabobank、Santander、SMBC、ING、ABN AMRO等十家银行组成的银团提供贷款支持;商业运营目标定于2028年3月底。",
    source_name: "Energy-Storage.News",
    source_url: "https://www.ess-news.com/2026/09/25/giga-storage-starts-construction-on-2-8-gwh-belgian-bess/"
  },
  {
    id: 18,
    country: "BR",
    date: "2026-09-25",
    title_en: "Minas Gerais Suspends Five More Environmental Licenses at Sigma Lithium's Mine",
    title_zh: "米纳斯吉拉斯州追加暂停Sigma Lithium矿区五项环境许可证",
    desc_en: "Following the federal court's September 4 suspension of Sigma Lithium's licenses over consultation rights of the nearby Baú Quilombola Community, Minas Gerais state authorities moved on September 24 to suspend five additional environmental operating licenses held by the company's Grota do Cirilo mine — Brazil's largest lithium operation — a decision welcomed the next day by federal deputy Célia Xakriabá. A court-appointed expert has 45 days to map the community's territory relative to the mine, while Sigma Lithium maintains the project falls outside the zone requiring free, prior, and informed consultation and continues to pursue relief through the courts.",
    desc_zh: "继联邦法院9月4日以邻近包基伦坡社区(Baú Quilombola)磋商权问题为由暂停Sigma Lithium许可证之后,米纳斯吉拉斯州政府9月24日进一步暂停该公司旗下巴西最大锂矿——Grota do Cirilo矿区的另外五项环境运营许可证,联邦众议员塞莉亚·扎克里亚巴(Célia Xakriabá)次日对此表示欢迎。法院指定的专家将有45天时间完成对社区领地与矿区关系的测绘工作,而Sigma Lithium坚持认为项目位于无需“自由、事先且知情同意”磋商的范围之外,并将继续通过司法途径寻求救济。",
    source_name: "PR Newswire",
    source_url: "https://www.prnewswire.com/news-releases/brazilian-congresswoman-applauds-suspension-of-sigma-lithiums-environmental-permits-302890396.html"
  },
  {
    id: 19,
    country: "TW",
    date: "2026-09-24",
    title_en: "Mercedes-Benz Secures Priority Access to ProLogium's Gen4 Solid-State Battery Cells",
    title_zh: "梅赛德斯-奔驰获得台湾辉能科技第四代固态电池优先测试权",
    desc_en: "Mercedes-Benz and Taiwanese battery maker ProLogium signed a joint testing agreement on September 24 giving the automaker priority access to evaluate ProLogium's newest Gen4 'Superfluidized' all-inorganic solid-state battery cells, which use a non-flammable ceramic electrolyte in place of a liquid one. The deal builds on a partnership dating back roughly a decade that already includes a Mercedes equity investment in ProLogium, and comes as Mercedes separately works with US-based Factorial Energy on solid-state cells; ProLogium is building a large-scale solid-state plant in Dunkirk, France, while Mercedes targets its first solid-state-powered production EV by 2030.",
    desc_zh: "梅赛德斯-奔驰9月24日与台湾电池制造商辉能科技(ProLogium)签署联合测试协议,获得优先测试其最新一代Gen4“超流态”全无机固态电池电芯的权利,该技术以不可燃的陶瓷电解质取代液态电解质。此次合作建立在双方约十年的合作基础之上,奔驰此前已对辉能进行股权投资;与此同时,奔驰也在与美国Factorial Energy并行推进固态电池研发。辉能正在法国敦刻尔克建设大型固态电池工厂,而奔驰计划到2030年推出首款搭载固态电池的量产电动车。",
    source_name: "GlobeNewswire",
    source_url: "https://www.globenewswire.com/news-release/2026/09/24/3368567/0/en/mercedes-benz-and-prologium-have-entered-into-a-joint-testing-agreement-including-a-preliminary-technology-evaluation-of-prologium-s-latest-gen4-superfluidized-all-inorganic-solid-.html"
  },
  {
    id: 20,
    country: "PT",
    date: "2026-09-23",
    title_en: "Portugal Postpones 1,050 MVA Battery Storage Auction to Refine Tender Terms",
    title_zh: "葡萄牙推迟1050兆伏安电池储能拍卖,以完善招标条款",
    desc_en: "Portugal's government delayed by several weeks the launch of tenders for 1,050 MVA of battery storage capacity that had been scheduled to open September 14, as regulators work through feedback from a public consultation on the terms. A 750 MVA stand-alone storage tender, run by the Directorate-General for Energy and Geology (DGEG), will let bidders claim 50-200 MVA at multiple grid connection points with a minimum four-hour duration, while a companion 300 MVA tender covers batteries co-located with renewable plants. Under the proposed framework, host municipalities would receive 30% of auction revenue, with the rest going to Portugal's national electricity system.",
    desc_zh: "葡萄牙政府将原定于9月14日启动的1050兆伏安电池储能招标推迟数周,以便监管部门消化此前公开征询收到的意见反馈。其中,由葡萄牙能源与地质总局(DGEG)负责的750兆伏安独立储能招标,允许投标方在电网多个接入点申请50至200兆伏安容量,且储能时长须不低于四小时;另一项300兆伏安招标则面向配套建设储能的可再生能源电站。根据拟议方案,拍卖收入的30%将分配给项目所在市镇,其余部分归入葡萄牙国家电力系统。",
    source_name: "Energy-Storage.News",
    source_url: "https://www.ess-news.com/2026/09/23/portugal-delays-1050-mva-battery-storage-auction/"
  },
  {
    id: 21,
    country: "CA",
    date: "2026-09-22",
    title_en: "Rock Tech Lithium Taps Siemens Canada to Build Digital Twin of Ontario Lithium Converter",
    title_zh: "Rock Tech Lithium携手西门子加拿大,为安大略锂转化厂打造数字孪生系统",
    desc_en: "Rock Tech Lithium and Siemens Canada signed agreements around September 22 to build a physics-based digital twin of Rock Tech's planned Red Rock lithium converter in northwestern Ontario, the first implementation step under a strategic memorandum of understanding the companies signed in March. The digital twin will model the plant's processes, energy flows, and material streams so Rock Tech can test and validate design, efficiency, and emissions choices before committing major capital, with Siemens also supporting process-control and automation architecture for the converter's feasibility study, which began in June and is due by mid-December. The companies plan to extend the digital twin across the project's full lifecycle, from engineering through construction and operations.",
    desc_zh: "Rock Tech Lithium与西门子加拿大约9月22日签署协议,将为公司计划在安大略省西北部建设的Red Rock锂转化厂打造基于物理模型的数字孪生系统,这是双方今年3月签署战略谅解备忘录后的首个落地实施步骤。该数字孪生系统将模拟工厂的工艺流程、能量与物料流动,使Rock Tech能够在投入大量资本前对设计方案、能效与排放选择进行测试和验证;西门子还将为该转化厂正在进行的可行性研究提供过程控制与自动化架构支持,该研究于6月启动,预计12月中旬完成。双方计划将数字孪生技术延伸至项目全生命周期,涵盖工程设计、建设施工直至运营阶段。",
    source_name: "PR Newswire",
    source_url: "https://www.prnewswire.com/news-releases/rock-tech-lithium-and-siemens-canada-sign-agreements-to-bring-advanced-german-engineering-to-ontario-lithium-converter-project-302885415.html"
  },
  {
    id: 22,
    country: "CL",
    date: "2026-09-22",
    title_en: "Chile Runs First Grid-Forming Tests at Engie's 48 MW/275 MWh Los Loros Battery",
    title_zh: "智利在Engie公司48兆瓦/275兆瓦时Los Loros储能电站开展首次电网构建型技术测试",
    desc_en: "Chile's National Electricity Coordinator carried out the country's first field tests of grid-forming battery technology around September 22 at Engie's Los Loros battery storage system in the Atacama region, working alongside Engie Chile and Huawei. One power block of the 48 MW/275 MWh system — co-located with the Los Loros solar plant and in commercial operation since late August — ran in grid-forming mode and helped form an isolated electrical island while holding stable voltage and frequency. The results will feed into verification criteria for integrating grid-forming batteries into Chile's national grid, which is adding storage rapidly to firm its fast-growing solar and wind fleet.",
    desc_zh: "智利国家电力协调中心约9月22日与Engie智利公司及华为合作,在Engie位于阿塔卡马地区的Los Loros储能电站开展该国首次电网构建型(grid-forming)电池技术现场测试。测试期间,这座与Los Loros光伏电站合建、8月底投入商业运营的48兆瓦/275兆瓦时储能系统其中一个功率单元以电网构建模式运行,协助形成孤岛电网并保持电压与频率稳定。测试结果将为电网构建型电池并入智利国家电网的验证标准提供依据,该国正加速部署储能以稳定快速增长的光伏与风电装机。",
    source_name: "Energy-Storage.News",
    source_url: "https://www.ess-news.com/2026/09/22/chile-tests-grid-forming-tech-at-48-mw-275-mwh-bess/"
  },
  {
    id: 23,
    country: "HU",
    date: "2026-09-22",
    title_en: "CATL Starts Trial Cell Production at €7.34 Billion Debrecen Plant in Hungary",
    title_zh: "宁德时代匈牙利德布勒森工厂启动电芯试生产,总投资73.4亿欧元",
    desc_en: "CATL began trial production of battery cells on September 22 at its Debrecen, Hungary plant, running the first two of its planned production lines to commission equipment and validate manufacturing processes ahead of mass production. Once complete, the 100 GWh facility will be CATL's largest production base outside China and its second European cell plant after Germany; the site has made battery modules since late 2024, with more than 537,000 produced to date. The milestone comes despite a temporary halt ordered September 2 at three of the plant's workshops after Hungarian regulators found elevated nickel exposure among workers.",
    desc_zh: "宁德时代9月22日在其匈牙利德布勒森工厂启动电池电芯试生产,首批两条产线投入运行,用于设备调试及工艺验证,为后续量产做准备。这座规划产能100吉瓦时的工厂建成后将成为宁德时代海外最大生产基地,也是继德国工厂之后的第二座欧洲电芯工厂;该基地自2024年底起生产电池模组,累计产量已超过53.7万套。此次试产启动之际,该工厂三个车间此前于9月2日曾因匈牙利监管部门发现工人镍暴露超标而一度被下令暂停作业。",
    source_name: "PR Newswire",
    source_url: "https://www.prnewswire.com/news-releases/catl-kicks-off-trial-production-of-battery-cells-in-hungary-302886109.html"
  },
  {
    id: 24,
    country: "NL",
    date: "2026-09-21",
    title_en: "RWE Takes Final Investment Decision on 400 MW/1.1 GWh Battery at Moerdijk, Netherlands",
    title_zh: "RWE对荷兰穆尔代克400兆瓦/1.1吉瓦时电池储能项目做出最终投资决定",
    desc_en: "German utility RWE announced on September 21 a final investment decision to build a 400 MW/1,100 MWh battery storage system using 208 containerized lithium-ion units at its Moerdijk power station site in Noord-Brabant — one of the largest battery systems in the Netherlands, able to cover the evening peak demand of roughly 500,000 households for nearly three hours. Under capacity-steering agreements with grid operator TenneT, the system will help relieve congestion near the Moerdijk-Noord substation and provide grid services such as inertia; construction is set to start in due course with commissioning planned for Q2 2028.",
    desc_zh: "德国能源企业RWE 9月21日宣布,已就在荷兰北布拉班特省穆尔代克(Moerdijk)电站厂址建设一套400兆瓦/1100兆瓦时电池储能系统做出最终投资决定,该系统由208个集装箱式锂离子电池单元组成,是荷兰规模最大的电池储能系统之一,可满足约50万户家庭晚间用电高峰近三小时的用电需求。根据与电网运营商TenneT签订的容量调度协议,该系统将协助缓解穆尔代克北部变电站附近的电网阻塞,并提供惯量等电网服务;项目将适时开工建设,商业运营计划于2028年第二季度实现。",
    source_name: "RWE",
    source_url: "https://www.rwe.com/en/press/rwe-generation/2026-09-21-rwe-to-build-400-mw-battery-to-ease-grid-congestion-in-noord-brabant/"
  },
  {
    id: 25,
    country: "JP",
    date: "2026-09-16",
    title_en: "Panasonic Energy Opens 'Energy Innovation Square' Battery R&D Hub in Osaka",
    title_zh: "松下能源在大阪启用“能源创新广场”电池研发中心",
    desc_en: "Panasonic Energy announced on September 16 the launch of Energy Innovation Square, a roughly 24,500-square-meter, six-floor battery research and development hub in Kadoma, Osaka, that will house about 500 employees working on material development, cell design, and prototyping. Working alongside the company's nearby Suminoe production development facility — together forming one of Japan's largest dedicated battery R&D operations with about 800 staff — the new hub is meant to cut development lead times by at least 15% and speed up next-generation cell and materials work for automotive and data-center applications, with technologies developed there deployed across Panasonic Energy's global plants, including its Nevada and Kansas facilities in the US.",
    desc_zh: "松下能源9月16日宣布启用“能源创新广场”(Energy Innovation Square),这座位于大阪门真市、建筑面积约2.45万平方米的六层电池研发中心将容纳约500名员工,负责材料开发、电芯设计与样品试制等工作。该中心与公司附近的住之江生产开发基地协同运作,两者合计约800名员工,构成日本最大的专业电池研发基地之一;新中心旨在将开发周期至少缩短15%,加快面向汽车与数据中心应用的下一代电芯及材料研发,相关技术成果将推广至松下能源全球工厂,包括其在美国内华达州与堪萨斯州的生产基地。",
    source_name: "Panasonic Newsroom",
    source_url: "https://news.panasonic.com/global/press/en260916-3"
  },
  {
    id: 26,
    country: "EG",
    date: "2026-09-16",
    title_en: "CATL Licenses Battery Pack Technology to Egypt's BME for First Local Pack Plant",
    title_zh: "宁德时代向埃及BME公司授权电池包技术,助力当地首座电池包工厂建设",
    desc_en: "CATL signed a cooperation agreement around September 16 with Egyptian manufacturer BME — founded by commercial vehicle maker MCV and automotive solutions provider Auto D — to license its battery pack technology and supply production equipment and technical training for what is described as Egypt's first local battery pack plant. The facility, requiring initial investment of more than 2 billion Egyptian pounds (roughly $39 million), will start with 1 GWh of annual capacity focused on packs for heavy commercial vehicles, with room to expand to 5 GWh under long-term plans; BME will source cells from CATL while handling the facility investment itself.",
    desc_zh: "宁德时代约9月16日与埃及电池制造商BME(由商用车企业MCV与汽车解决方案提供商Auto D共同创立)签署合作协议,授权其电池包技术并提供生产设备与技术培训,支持建设据称是埃及首座本地电池包工厂。该工厂初期投资超过20亿埃及镑(约3900万美元),首期年产能1吉瓦时,主要生产重型商用车电池包,长期规划可扩产至5吉瓦时;BME将自行承担工厂投资并向宁德时代采购电芯。",
    source_name: "CnEVPost",
    source_url: "https://cnevpost.com/2026/09/16/catl-deal-egypt-bme-battery-pack-production/"
  },
  {
    id: 27,
    country: "MA",
    date: "2026-09-16",
    title_en: "Morocco's OCP Switches On the Country's First Large-Scale Battery Storage System",
    title_zh: "摩洛哥OCP集团启用该国首套大型电池储能系统",
    desc_en: "Moroccan phosphate giant OCP Group energized a 25 MW / 125 MWh lithium iron phosphate battery storage system at its Benguerir mining site on September 14 — the country's first large-scale BESS installation. Supplied and commissioned by China's Envision under a contract signed in late 2025, the MAD 170 million (about $18 million) system is paired with the site's existing 67 MWp solar plant and is expected to cut peak-hour electricity costs by roughly 25% while helping regulate grid frequency. It is part of OCP's plan to invest $13 billion in clean energy through 2027 and run all its industrial operations on clean power by then.",
    desc_zh: "摩洛哥磷酸盐巨头OCP集团9月14日在其本格里尔(Benguerir)矿区启用一套25兆瓦/125兆瓦时磷酸铁锂电池储能系统,这是摩洛哥首套大型电池储能装置。该系统由中国远景能源(Envision)依据2025年底签署的合同供应并完成调试,总投资1.7亿迪拉姆(约合1800万美元),与矿区现有67兆瓦光伏电站配套运行,预计可将高峰时段用电成本降低约25%,同时协助电网调频。该项目是OCP到2027年投资130亿美元发展清洁能源计划的一部分,目标是届时实现全部工业运营使用清洁能源。",
    source_name: "Energy-Storage.News",
    source_url: "https://www.ess-news.com/2026/09/16/ocp-deploys-25-mw-125-mwh-lfp-battery-at-moroccan-phosphate-mine/"
  },
  {
    id: 28,
    country: "SA",
    date: "2026-09-15",
    title_en: "Gotion High-Tech Wins 6 GWh Battery Storage Order for Three Saudi Arabia Sites",
    title_zh: "国轩高科获沙特阿拉伯三个项目6吉瓦时电池储能订单",
    desc_en: "Chinese battery maker Gotion High-Tech said around September 15 it has secured an order to supply 6 GWh of battery energy storage systems for three large-scale sites in Saudi Arabia, marking its entry into Middle East utility-scale storage. The company will deploy its Qianyuan Smart Energy Storage System, built for stable operation across a -30°C to 55°C range, to store surplus daytime solar power and dispatch it back to the grid during peak demand; Gotion said the projects have entered substantive construction as one of the first batches of large-scale battery storage to break ground in the kingdom.",
    desc_zh: "中国电池企业国轩高科约9月15日宣布,获得沙特阿拉伯三个大型项目共计6吉瓦时的电池储能系统供应订单,标志着公司正式进入中东大型储能市场。公司将部署其“乾元”智慧储能系统,该系统可在零下30°C至55°C温度范围内稳定运行,用于存储白天富余光伏电力并在用电高峰时段回馈电网;国轩高科表示,相关项目已进入实质性施工阶段,是沙特首批开工建设的大型电池储能项目之一。",
    source_name: "Battery-News",
    source_url: "https://battery-news.de/en/2026/09/16/gotion-high-tech-to-supply-6-gwh-of-battery-storage-in-saudi-arabia/"
  },
  {
    id: 29,
    country: "GB",
    date: "2026-09-15",
    title_en: "UK's Palmer Energy and Slovakia's InoBat Sign Pan-European Battery Storage Supply Pact",
    title_zh: "英国Palmer Energy与斯洛伐克InoBat签署泛欧电池储能供应合作协议",
    desc_en: "UK energy firm Palmer Energy Technology and Slovak battery maker InoBat signed a collaboration agreement around September 15 to supply battery energy storage systems across Europe, with Palmer taking the lead in the UK and Ireland and InoBat leading in continental Europe and North America; the deal includes arrangements for Palmer to supply InoBat with storage units through the rest of 2026. It comes as the UK government pursues a 27 GW battery storage target, underscoring growing British demand for grid-scale storage capacity to back its renewables buildout.",
    desc_zh: "英国能源企业Palmer Energy Technology与斯洛伐克电池制造商InoBat于9月15日前后签署合作协议,双方将在欧洲范围内供应电池储能系统:Palmer主导英国及爱尔兰市场,InoBat主导欧洲大陆及北美市场;协议还包括Palmer在2026年剩余时间内向InoBat供应储能设备的安排。此次合作正值英国政府力推27吉瓦电池储能目标之际,凸显英国为支撑可再生能源建设而对电网级储能容量日益增长的需求。",
    source_name: "Politics.co.uk",
    source_url: "https://www.politics.co.uk/opinion-former/press-release/2026/09/15/uk-battery-firm-palmer-energy-signs-european-supply-deal-as-government-chases-27gw-storage-target/"
  },
  {
    id: 30,
    country: "RO",
    date: "2026-09-15",
    title_en: "Romania Finalizes Rules for RON 400 Million Home Battery Storage Subsidy",
    title_zh: "罗马尼亚敲定家庭电池储能补贴细则,预算4亿列伊",
    desc_en: "Romania's Ministry of Environment, Waters and Forests finalized the rules for a national battery-storage subsidy scheme on September 15, after a public consultation that drew more than 200 submissions. Administered by the Administrația Fondului pentru Mediu, the RON 400 million (about $87.8 million) program will cover up to 75% of costs for prosumers with a grid-connected solar system who add battery storage, with grants capped at RON 15,000 including VAT. The final rules lowered the minimum eligible storage size from 12 kWh to 10 kWh and raised the maximum eligible cost standard to RON 1,500 per kWh, with applications ranked by score rather than processed first-come, first-served.",
    desc_zh: "罗马尼亚环境、水利与森林部于9月15日敲定了全国家庭电池储能补贴计划的最终细则,此前该计划历经公开征询,收到200多份意见反馈。该计划由罗马尼亚环境基金管理局(AFM)负责实施,预算为4亿列伊(约合8780万美元),面向已并网太阳能系统的产消者(prosumer),补贴最高可覆盖新增电池储能系统成本的75%,单户补贴上限为1.5万列伊(含增值税)。最终规则将最低申请储能容量由12千瓦时降至10千瓦时,并将每千瓦时最高认定成本上调至1500列伊,申请将按评分排序而非先到先得。",
    source_name: "Energy-Storage.News",
    source_url: "https://www.ess-news.com/2026/09/15/romania-finalizes-rules-for-national-battery-storage-subsidy-program/"
  },
  {
    id: 31,
    country: "AR",
    date: "2026-09-15",
    title_en: "Lithium Argentina Closes $180 Million Convertible Note Investment From Ganfeng",
    title_zh: "力拓阿根廷锂业完成赣锋锂业1.8亿美元可转换票据投资交割",
    desc_en: "Lithium Argentina said around September 15 it has closed a $180 million strategic investment from China's Ganfeng Lithium Group, structured as a six-year unsecured convertible note carrying a 4% annual coupon and convertible into shares at $12.50 apiece. Proceeds, together with cash on hand, will go toward fully repaying $259 million of convertible notes due January 2027. If fully converted, the note would lift Ganfeng's stake in Lithium Argentina from about 9.6% to roughly 16.1%; the two companies already jointly operate the Cauchari-Olaroz brine project and are working to finalize a joint venture over the Pozuelos-Pastos Grandes project in Salta province by the end of September.",
    desc_zh: "力拓阿根廷锂业(Lithium Argentina)约9月15日宣布,已完成中国赣锋锂业集团1.8亿美元战略投资的交割,该投资以六年期无抵押可转换票据形式发行,年息4%,可按每股12.50美元的价格转换为公司普通股。所得资金连同公司现有现金将用于全额偿还2027年1月到期的2.59亿美元可转换票据。若该票据全部转股,赣锋锂业在力拓阿根廷锂业的持股比例将从约9.6%提升至约16.1%;两家公司目前已共同运营Cauchari-Olaroz盐湖锂项目,并正推进就萨尔塔省Pozuelos-Pastos Grandes项目组建合资企业,目标在9月底前完成。",
    source_name: "GlobeNewswire",
    source_url: "https://www.globenewswire.com/news-release/2026/09/15/3361860/0/en/lithium-argentina-announces-closing-of-180m-strategic-investment-from-ganfeng.html"
  }
];

// Country metadata: flag emoji + bilingual names, in a sensible display order.
const COUNTRIES = [
  { code: "CN", flag: "🇨🇳", name_en: "China", name_zh: "中国" },
  { code: "US", flag: "🇺🇸", name_en: "United States", name_zh: "美国" },
  { code: "KR", flag: "🇰🇷", name_en: "South Korea", name_zh: "韩国" },
  { code: "JP", flag: "🇯🇵", name_en: "Japan", name_zh: "日本" },
  { code: "TW", flag: "🇹🇼", name_en: "Taiwan", name_zh: "台湾" },
  { code: "DE", flag: "🇩🇪", name_en: "Germany", name_zh: "德国" },
  { code: "CH", flag: "🇨🇭", name_en: "Switzerland", name_zh: "瑞士" },
  { code: "SE", flag: "🇸🇪", name_en: "Sweden", name_zh: "瑞典" },
  { code: "NO", flag: "🇳🇴", name_en: "Norway", name_zh: "挪威" },
  { code: "FI", flag: "🇫🇮", name_en: "Finland", name_zh: "芬兰" },
  { code: "EU", flag: "🇪🇺", name_en: "European Union", name_zh: "欧盟" },
  { code: "FR", flag: "🇫🇷", name_en: "France", name_zh: "法国" },
  { code: "GB", flag: "🇬🇧", name_en: "United Kingdom", name_zh: "英国" },
  { code: "NL", flag: "🇳🇱", name_en: "Netherlands", name_zh: "荷兰" },
  { code: "BE", flag: "🇧🇪", name_en: "Belgium", name_zh: "比利时" },
  { code: "IT", flag: "🇮🇹", name_en: "Italy", name_zh: "意大利" },
  { code: "SK", flag: "🇸🇰", name_en: "Slovakia", name_zh: "斯洛伐克" },
  { code: "HU", flag: "🇭🇺", name_en: "Hungary", name_zh: "匈牙利" },
  { code: "RO", flag: "🇷🇴", name_en: "Romania", name_zh: "罗马尼亚" },
  { code: "ES", flag: "🇪🇸", name_en: "Spain", name_zh: "西班牙" },
  { code: "PT", flag: "🇵🇹", name_en: "Portugal", name_zh: "葡萄牙" },
  { code: "PL", flag: "🇵🇱", name_en: "Poland", name_zh: "波兰" },
  { code: "UA", flag: "🇺🇦", name_en: "Ukraine", name_zh: "乌克兰" },
  { code: "BG", flag: "🇧🇬", name_en: "Bulgaria", name_zh: "保加利亚" },
  { code: "IN", flag: "🇮🇳", name_en: "India", name_zh: "印度" },
  { code: "ID", flag: "🇮🇩", name_en: "Indonesia", name_zh: "印度尼西亚" },
  { code: "MY", flag: "🇲🇾", name_en: "Malaysia", name_zh: "马来西亚" },
  { code: "AU", flag: "🇦🇺", name_en: "Australia", name_zh: "澳大利亚" },
  { code: "CA", flag: "🇨🇦", name_en: "Canada", name_zh: "加拿大" },
  { code: "MX", flag: "🇲🇽", name_en: "Mexico", name_zh: "墨西哥" },
  { code: "CL", flag: "🇨🇱", name_en: "Chile", name_zh: "智利" },
  { code: "BR", flag: "🇧🇷", name_en: "Brazil", name_zh: "巴西" },
  { code: "MA", flag: "🇲🇦", name_en: "Morocco", name_zh: "摩洛哥" },
  { code: "AR", flag: "🇦🇷", name_en: "Argentina", name_zh: "阿根廷" },
  { code: "ZW", flag: "🇿🇼", name_en: "Zimbabwe", name_zh: "津巴布韦" },
  { code: "SA", flag: "🇸🇦", name_en: "Saudi Arabia", name_zh: "沙特阿拉伯" },
  { code: "EG", flag: "🇪🇬", name_en: "Egypt", name_zh: "埃及" },
  { code: "CI", flag: "🇨🇮", name_en: "Côte d'Ivoire", name_zh: "科特迪瓦" }
];

// US battery factory map data — every type/chemistry, compiled from company and
// state economic-development announcements. x/y are schematic map coordinates,
// not precise lat/long.
const FACTORIES = [
  { id: 1, x: 97.1, y: 246.8, status: "hiring", company_en: "Tesla", company_zh: "特斯拉", site_en: "Gigafactory Nevada (battery cells)", site_zh: "内华达超级工厂(电芯)", city_en: "Sparks, NV", city_zh: "斯帕克斯,内华达州", note_en: "Hiring ~2,000-3,000 roles with Panasonic for Semi/Cybertruck battery ramp-up.", note_zh: "为配合Semi与Cybertruck电池产能爬坡,正与松下共同招聘约2000-3000个岗位。", url: "https://www.tesla.com/careers/search/?region=United+States" },
  { id: 2, x: 102.2, y: 248.2, status: "hiring", company_en: "Redwood Materials", company_zh: "Redwood Materials", site_en: "Battery materials & recycling campus", site_zh: "电池材料与回收园区", city_en: "McCarran, NV", city_zh: "麦卡伦,内华达州", note_en: "120+ open roles across engineering, operations, and manufacturing.", note_zh: "工程、运营、生产等岗位在招超120个。", url: "https://job-boards.greenhouse.io/redwoodmaterials" },
  { id: 3, x: 470.4, y: 509.5, status: "hiring", company_en: "Tesla", company_zh: "特斯拉", site_en: "Gigafactory Texas (cell & pack production)", site_zh: "德克萨斯超级工厂(电芯与电池包)", city_en: "Austin, TX", city_zh: "奥斯汀,德克萨斯州", note_en: "Actively hiring battery cell production and engineering roles.", note_zh: "正在招聘电芯生产及工程相关岗位。", url: "https://www.tesla.com/careers/search/?region=United+States" },
  { id: 4, x: 219.8, y: 442.8, status: "soon", company_en: "American Battery Factory (ABF)", company_zh: "美国电池工厂(ABF)", site_en: "LFP cell gigafactory", site_zh: "磷酸铁锂电芯超级工厂", city_en: "Tucson, AZ", city_zh: "图森,亚利桑那州", note_en: "Early-stage hiring (~60 staff now), scaling toward 1,000 as construction phases complete.", note_zh: "处于早期招聘阶段(目前约60人),随建设推进将扩大至约1000人。", url: "https://americanbatteryfactory.com/careers/" },
  { id: 5, x: 211.2, y: 417.7, status: "hiring", company_en: "LG Energy Solution", company_zh: "LG新能源", site_en: "Standalone cylindrical & LFP ESS battery complex", site_zh: "独立圆柱电芯与磷酸铁锂储能电池综合体", city_en: "Queen Creek, AZ", city_zh: "皇后溪,亚利桑那州", note_en: "Hiring underway ahead of 2026 mass production.", note_zh: "为2026年量产招聘正在进行。", url: "https://www.lgensol.com/en/careers" },
  { id: 6, x: 522.5, y: 310.6, status: "hiring", company_en: "Panasonic Energy", company_zh: "松下能源", site_en: "EV battery gigafactory", site_zh: "电动车电池超级工厂", city_en: "De Soto, KS", city_zh: "迪索托,堪萨斯州", note_en: "~1,400 employed; hosting hiring events for several hundred more entry-level machine technicians.", note_zh: "现有员工约1400人;正举办招聘活动,计划再招募数百名入门级机械技术员。", url: "https://careers.na.panasonic.com/energy" },
  { id: 7, x: 668.0, y: 215.0, status: "hiring", company_en: "LG Energy Solution", company_zh: "LG新能源", site_en: "LFP / ESS battery plant", site_zh: "磷酸铁锂储能电池工厂", city_en: "Holland, MI", city_zh: "霍兰,密歇根州", note_en: "Hiring engineering technicians, electricians, and production supervisors.", note_zh: "正招聘工程技术员、电工及生产主管等岗位。", url: "https://www.lgensol.com/en/careers" },
  { id: 8, x: 691.5, y: 213.7, status: "hiring", company_en: "Ultium Cells (GM / LG Energy Solution JV)", company_zh: "Ultium Cells(通用汽车与LG新能源合资)", site_en: "EV battery cell plant", site_zh: "电动车电芯工厂", city_en: "Delta Township (Lansing), MI", city_zh: "兰辛(特尔塔镇),密歇根州", note_en: "Part of 50+ open roles across Ultium's three US plants.", note_zh: "Ultium美国三座工厂合计在招岗位超50个。", url: "https://ev.careers/companies/ultium-cells-llc-1618317" },
  { id: 9, x: 713.0, y: 222.7, status: "hiring", company_en: "Our Next Energy (ONE)", company_zh: "Our Next Energy(ONE)", site_en: "ONE Circle LFP battery campus", site_zh: "ONE Circle磷酸铁锂电池园区", city_en: "Van Buren Township, MI", city_zh: "范布伦镇,密歇根州", note_en: "Hiring toward 2,112 jobs as the plant ramps to 20 GWh by late 2027.", note_zh: "工厂计划2027年底前产能提升至20吉瓦时,招聘岗位最终将达2112个。", url: "https://recruiting.ultipro.com/OUR1002ONXE/JobBoard/5c7eeefc-e61c-417a-8468-f976a704a34d/?q=&o=postedDateDesc&w=&wc=&we=&wpst=" },
  { id: 10, x: 760.4, y: 238.5, status: "hiring", company_en: "Ultium Cells (GM / LG Energy Solution JV)", company_zh: "Ultium Cells(通用汽车与LG新能源合资)", site_en: "EV battery cell plant", site_zh: "电动车电芯工厂", city_en: "Warren, OH", city_zh: "沃伦,俄亥俄州", note_en: "Part of 50+ open roles across Ultium's three US plants.", note_zh: "Ultium美国三座工厂合计在招岗位超50个。", url: "https://ev.careers/companies/ultium-cells-llc-1618317" },
  { id: 11, x: 767.3, y: 256.3, status: "hiring", company_en: "Form Energy", company_zh: "Form Energy", site_en: "Iron-air battery factory (Form Factory 1)", site_zh: "铁空气电池工厂(Form Factory 1)", city_en: "Weirton, WV", city_zh: "韦尔顿,西弗吉尼亚州", note_en: "199 open roles company-wide; scaling toward 750+ jobs as the former steel-mill site converts to multi-day storage cell production.", note_zh: "公司全线在招岗位199个;原钢厂旧址正改造为多日储能电芯生产基地,招聘将扩大至750人以上。", url: "https://formenergy.com/careers/" },
  { id: 12, x: 669.8, y: 376.7, status: "hiring", company_en: "Ultium Cells (GM / LG Energy Solution JV)", company_zh: "Ultium Cells(通用汽车与LG新能源合资)", site_en: "EV battery plant, converting to prismatic LMR cells by 2028", site_zh: "电动车电芯工厂,2028年前改造为棱柱形LMR电芯产线", city_en: "Spring Hill, TN", city_zh: "斯普林希尔,田纳西州", note_en: "~$1B LMR-cell conversion expected to add ~500 jobs to the ~1,200-person site.", note_zh: "约10亿美元的LMR电芯改造项目预计为现有约1200人的工厂新增约500个岗位。", url: "https://ev.careers/companies/ultium-cells-llc-1618317" },
  { id: 13, x: 625.6, y: 386.8, status: "soon", company_en: "BlueOval SK (Ford / SK On JV)", company_zh: "BlueOval SK(福特与SK On合资)", site_en: "EV battery plant at BlueOval City", site_zh: "BlueOval City电动车电池工厂", city_en: "Stanton, TN", city_zh: "斯坦顿,田纳西州", note_en: "Commercial production targeted for 2026; hiring ramps ahead of startup.", note_zh: "商业化生产目标为2026年,招聘正随投产临近逐步展开。", url: "https://www.blueovalsk.com/careers" },
  { id: 14, x: 683.8, y: 332.7, status: "soon", company_en: "Ford Motor Company", company_zh: "福特汽车", site_en: "BlueOval Battery Park (former BlueOval SK plant, pivoting to storage)", site_zh: "BlueOval电池园区(原BlueOval SK工厂,转型储能生产)", city_en: "Glendale, KY", city_zh: "格伦代尔,肯塔基州", note_en: "Original JV plant paused; Ford hiring salaried staff from early 2026, hourly operators from 2027.", note_zh: "原合资工厂已暂停;福特将于2026年初招聘受薪员工,2027年起招聘时薪操作员。", url: "https://www.careers.ford.com/search-jobs/United%20States?orgIds=48560&alp=6252001&alt=2" },
  { id: 15, x: 675.2, y: 348.2, status: "hiring", company_en: "Envision AESC", company_zh: "远景AESC", site_en: "EV battery gigafactory", site_zh: "电动车电池超级工厂", city_en: "Bowling Green, KY", city_zh: "鲍灵格林,肯塔基州", note_en: "Building toward ~2,000 jobs; $2B gigafactory under construction.", note_zh: "20亿美元超级工厂建设中,目标创造约2000个就业岗位。", url: "https://ev.careers/companies/aesc-1755150" },
  { id: 16, x: 663.9, y: 240.3, status: "unclear", company_en: "Samsung SDI", company_zh: "三星SDI", site_en: "EV battery cell plant (formerly a GM joint venture)", site_zh: "电动车电芯工厂(原通用汽车合资项目)", city_en: "New Carlisle, IN", city_zh: "新卡莱尔,印第安纳州", note_en: "Construction ahead of schedule after Samsung SDI took full ownership from GM; public hiring timeline not yet detailed.", note_zh: "三星SDI已从通用汽车手中接管全部股权,建设进度提前;具体招聘时间表尚未公开。", url: "https://www.samsungcareers.com/" },
  { id: 17, x: 673.0, y: 267.4, status: "hiring", company_en: "Samsung SDI / Stellantis JV (StarPlus Energy)", company_zh: "三星SDI与Stellantis合资(StarPlus Energy)", site_en: "Two EV / LFP battery plants", site_zh: "两座电动车及磷酸铁锂电池工厂", city_en: "Kokomo, IN", city_zh: "科科莫,印第安纳州", note_en: "LFP line starts September 2026; second plant ramps toward 2027.", note_zh: "磷酸铁锂产线将于2026年9月投产,第二座工厂预计2027年逐步达产。", url: "https://starplusenergyus.com/careers" },
  { id: 18, x: 737.3, y: 404.6, status: "hiring", company_en: "SK On (SK Battery America)", company_zh: "SK On(SK电池美国)", site_en: "EV battery plant", site_zh: "电动车电池工厂", city_en: "Commerce, GA", city_zh: "康默斯,佐治亚州", note_en: "Still hiring production, quality, and logistics roles despite 2026 layoffs amid EV demand slowdown.", note_zh: "尽管2026年因电动车需求放缓而裁员,仍在招聘生产、质量及物流等岗位。", url: "https://www.skbatteryamerica.com/" },
  { id: 19, x: 780.8, y: 446.4, status: "hiring", company_en: "Hyundai Motor Group / LG Energy Solution JV (HL-GA)", company_zh: "现代汽车集团与LG新能源合资(HL-GA)", site_en: "EV battery plant", site_zh: "电动车电池工厂", city_en: "Bryan County, GA", city_zh: "布莱恩县,佐治亚州", note_en: "Production started early 2026; hiring continues toward 8,500 jobs over 8 years.", note_zh: "已于2026年初投产,招聘将持续推进,未来8年目标创造8500个岗位。", url: "https://www.lgensol.com/en/careers" },
  { id: 20, x: 802.5, y: 356.6, status: "hiring", company_en: "Toyota", company_zh: "丰田", site_en: "Toyota Battery Manufacturing, North Carolina (TBMNC)", site_zh: "丰田电池制造北卡罗来纳工厂(TBMNC)", city_en: "Liberty, NC", city_zh: "利伯蒂,北卡罗来纳州", note_en: "900+ employed already; hundreds more hired yearly toward 5,100 jobs.", note_zh: "现有员工已超900人,未来每年还将新增数百个岗位,目标达5100人。", url: "https://careers.toyota.com/us/en/toyota-nc-operations-program" },
  { id: 21, x: 815.9, y: 354.7, status: "hiring", company_en: "Forge Nano / Forge Battery", company_zh: "Forge Nano / Forge Battery", site_en: "\"America's Battery Gigafactory\" expansion", site_zh: "“美国电池超级工厂”扩建项目", city_en: "Morrisville, NC", city_zh: "莫里斯维尔,北卡罗来纳州", note_en: "$100M DOE-backed expansion broke ground August 2026; Samsung SDI signed as an offtake customer.", note_zh: "获美国能源部1亿美元资助的扩建项目已于2026年8月动工;三星SDI已签约成为采购客户。", url: "https://forge-nano.breezy.hr/" },
  { id: 22, x: 834.0, y: 349.2, status: "hiring", company_en: "Natron Energy", company_zh: "Natron Energy", site_en: "Sodium-ion battery gigafactory", site_zh: "钠离子电池超级工厂", city_en: "Edgecombe County, NC", city_zh: "埃奇科姆县,北卡罗来纳州", note_en: "First US sodium-ion gigafactory; scaling toward 1,000+ jobs at full capacity.", note_zh: "美国首座钠离子电池超级工厂,满产后招聘规模将超1000人。", url: "https://natron.energy/careers/" },
  { id: 23, x: 805.5, y: 394.4, status: "hiring", company_en: "Envision AESC", company_zh: "远景AESC", site_en: "EV battery cell plant (BMW supplier)", site_zh: "电动车电芯工厂(宝马供应商)", city_en: "Florence, SC", city_zh: "弗洛伦斯,南卡罗来纳州", note_en: "Building toward 1,620 jobs as 2026 production start approaches.", note_zh: "随着2026年投产临近,招聘将扩大至1620个岗位。", url: "https://ev.careers/companies/aesc-1755150" },
  { id: 24, x: 799.6, y: 421.0, status: "soon", company_en: "Redwood Materials", company_zh: "Redwood Materials", site_en: "Cathode & anode materials campus", site_zh: "正极与负极材料园区", city_en: "Ridgeville, SC", city_zh: "里奇维尔,南卡罗来纳州", note_en: "Future-roles hiring underway ahead of ~1,500 planned jobs.", note_zh: "面向约1500个规划岗位的“未来职位”招聘已启动。", url: "https://job-boards.greenhouse.io/redwoodmaterials" },
  { id: 25, x: 676.8, y: 370.8, status: "hiring", company_en: "FIXX Energy", company_zh: "FIXX Energy", site_en: "Battery plant (former Nissan/AESC site), pivoting to energy storage", site_zh: "电池工厂(原日产/AESC工厂),转型生产储能电池", city_en: "Smyrna, TN", city_zh: "士麦那,田纳西州", note_en: "Acquired from AESC in April 2026; hiring process engineers, QA technologists, and manufacturing technicians at the former Nissan Leaf battery plant.", note_zh: "2026年4月从AESC收购;正在原日产聆风电池工厂招聘工艺工程师、质量检测技术员及生产技术员等岗位。", url: "https://fixxenergy.com/" },
  { id: 26, x: 642.5, y: 252.8, status: "hiring", company_en: "Gotion", company_zh: "国轩高科", site_en: "Battery & energy storage system plant (five production lines)", site_zh: "电池及储能系统工厂(五条产线)", city_en: "Manteno, IL", city_zh: "曼特诺,伊利诺伊州", note_en: "Ramping from ~300 to 450 employees by end of 2025, targeting 1,400 in 2026 and up to 2,600 long term.", note_zh: "员工数量将从约300人增至2025年底的450人,2026年目标达1400人,长期规划最高2600人。", url: "https://job-boards.greenhouse.io/gotion?offices%5B%5D=4057589002" },
  { id: 27, x: 83.2, y: 106.5, status: "hiring", company_en: "ESS Inc", company_zh: "ESS Inc", site_en: "Iron flow battery factory (headquarters)", site_zh: "铁液流电池工厂(总部)", city_en: "Wilsonville, OR", city_zh: "威尔逊维尔,俄勒冈州", note_en: "Tripling production capacity with US Export-Import Bank backing; hiring engineering technicians and production roles.", note_zh: "在美国进出口银行支持下将产能提升至三倍;正在招聘工程技术员及生产相关岗位。", url: "https://essinc.com/careers/" },
  { id: 28, x: 780.3, y: 254.7, status: "hiring", company_en: "Eos Energy Enterprises", company_zh: "Eos Energy Enterprises", site_en: "Znyth zinc battery factory", site_zh: "Znyth锌电池工厂", city_en: "Turtle Creek, PA", city_zh: "特特尔克里克,宾夕法尼亚州", note_en: "Hiring manufacturing engineers, electrical technicians, and machine operators for zinc battery energy storage production.", note_zh: "正在为锌电池储能生产招聘制造工程师、电气技术员及设备操作员等岗位。", url: "https://eose.com/careers/" }
];